# pyinstaller 로 exe 를 build 하기 위한 설정

# 1. 메인 파일 이름을 지정하세요.
main_file = 'main.py'

# 2. 데이타 파일들을 지정하세요.
data_files = [
    'ball.png','bgm.mp3','cloud.png','ENCR10B.TTF','End.png','grass.png','map.PNG',
    'move.wav','NetBottom.PNG','NetTOP.PNG','Pikachu.png','Pikachu_R.png','spike.wav',
    'test.png','Title.png','touch.wav'
]

# 3. 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
]

